version: "3.8"

services:
  proxy:
    container_name: nginx-proxy
    build:
      context: ./containers/nginx
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
  www:
    container_name: apache-www
    build:
      context: ./containers/apache
    volumes:
      - ./html:/usr/local/apache2/htdocs
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: host
    